
package service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PollTranslatorDSOLService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8088/poll-translator/?wsdl")
public class PollTranslatorDSOLService
    extends Service
{

    private final static URL POLLTRANSLATORDSOLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(service.PollTranslatorDSOLService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = service.PollTranslatorDSOLService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8088/poll-translator/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8088/poll-translator/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        POLLTRANSLATORDSOLSERVICE_WSDL_LOCATION = url;
    }

    public PollTranslatorDSOLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PollTranslatorDSOLService() {
        super(POLLTRANSLATORDSOLSERVICE_WSDL_LOCATION, new QName("http://service/", "PollTranslatorDSOLService"));
    }

    /**
     * 
     * @return
     *     returns PollTranslator
     */
    @WebEndpoint(name = "PollTranslatorDSOLPort")
    public PollTranslator getPollTranslatorDSOLPort() {
        return super.getPort(new QName("http://service/", "PollTranslatorDSOLPort"), PollTranslator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PollTranslator
     */
    @WebEndpoint(name = "PollTranslatorDSOLPort")
    public PollTranslator getPollTranslatorDSOLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "PollTranslatorDSOLPort"), PollTranslator.class, features);
    }

}
