
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PollTranslator", targetNamespace = "http://service/")
@XmlSeeAlso({
    com.doodle.xsd1.ObjectFactory.class,
    service.ObjectFactory.class
})
public interface PollTranslator {


    /**
     * 
     * @param pollId
     * @param language
     * @return
     *     returns service.Poll
     */
    @WebMethod
    @WebResult(name = "translatedPoll", targetNamespace = "")
    @RequestWrapper(localName = "getTranslatedPoll", targetNamespace = "http://service/", className = "service.GetTranslatedPoll")
    @ResponseWrapper(localName = "getTranslatedPollResponse", targetNamespace = "http://service/", className = "service.GetTranslatedPollResponse")
    public Poll getTranslatedPoll(
        @WebParam(name = "pollId", targetNamespace = "")
        String pollId,
        @WebParam(name = "language", targetNamespace = "")
        String language);

}
